app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='app-home'),
    path('login/', views.login_views, name='app-login'),
    path('logout/', views.logout_views, name='app-logout'),
    path('student/',views.get_student_view),
    path('teacher/',views.get_teacher_view),
    path('coordinator/',views.get_coordinator_view),
    path('course/',views.get_course_view),
    path('create-user/',views.create_user, name='app-create_user'),

]

composeexample/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.

#Model Course
class Course(models.Model):

    name = models.CharField(max_length=30)
    description = models.CharField(max_length=200)
    teacher = models.ForeignKey(User,  null = True, related_name = "course", on_delete = models.PROTECT, verbose_name = "teacher")

    def str(self):
        return self.name, self.description


class Promotion(models.Model):
    year = models.IntegerField(default=datetime.now().year)
    students = models.ManyToManyField(User, related_name = "promotion", verbose_name = "students")
    courses = models.ManyToManyField(Course, related_name = "promotion", verbose_name = "courses")

    def str(self):
        return self.year

app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError

class SignUpForm(UserCreationForm):
    CHOICES=[('student','student'),
         ('teacher','teacher'),
         ('coordinator','coordinator')]
    username = forms.CharField(label='Username', min_length=3, max_length=150)
    first_name = forms.CharField(max_length=32, label='First name')
    last_name=forms.CharField( max_length=32, label='Last name')
    email=forms.EmailField(max_length=64, label='Email')
    password1=forms.CharField(widget=forms.PasswordInput,label='Password')
    password2=forms.CharField(widget=forms.PasswordInput, label='Password Verification')
    promotion=forms.CharField(max_length=64, label='Promotion', required=False)
    user_type = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect(), label='User type')

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email',)

app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from .forms import SignUpForm
from django.contrib.auth.models import Group, Permission
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from .models import Course
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import permission_required

def login_views(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            messages.success(request, f'Bienvenu {username} !')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
            return redirect('app-home')
    else:
        form = AuthenticationForm()
    return render(request, 'app/login.html', {'form': form})

def logout_views(request):
    logout(request)
    messages.info(request, f'Vous avez été déconnecté!')
    return redirect('/login')

def create_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.save()
            username = form.cleaned_data.get('username')
            user_type = form.cleaned_data.get('user_type')
            print(user_type)
            if user_type == 'student':
                grp_student, created = Group.objects.get_or_create(name="Student")
                if created:
                    add_permissions_to_group_student(grp_student)
                user.groups.add(grp_student)
            elif user_type == 'teacher':
                grp_teacher, created = Group.objects.get_or_create(name="Teacher")
                if created:
                    add_permissions_to_group_teacher(grp_teacher)
                user.groups.add(grp_teacher)
            else:
                grp_coordinator, created = Group.objects.get_or_create(name="Coordinator")
                if created:
                    add_permissions_to_group_coordinator(grp_coordinator)
                user.groups.add(grp_coordinator)

            messages.success(request, f'User created {username} !')
            return HttpResponseRedirect(request.path_info)
    else:
        form = SignUpForm()
    return render(request, 'app/create-user.html', {'form': form})

def index(request):
    grp_student, created = Group.objects.get_or_create(name="Student")
    print(grp_student, created)
    return render(request, 'app/home.html')

def get_student_view(request):
    return render(request, 'student/student.html')

def get_teacher_view(request):
    return render(request, 'teacher/teacher.html')

def get_coordinator_view(request):
    return render(request, 'coordinator/coordinator.html')

def get_course_view(request):
    courses = Course.objects.all()
    return render(request, 'app/course/course.html', {'courses': courses})



def add_permissions_to_group_student(grp_student):
    permission_can_read_course = Permission.objects.get(name="Can view course")
    permission_can_read_promotion = Permission.objects.get(name="Can view promotion")

    grp_student.permissions.add(permission_can_read_course, permission_can_read_promotion)

def add_permissions_to_group_teacher(grp_teacher):
    permission_can_read_course = Permission.objects.get(name="Can view course")
    permission_can_read_promotion = Permission.objects.get(name="Can view promotion")

    grp_teacher.permissions.add(permission_can_read_course, permission_can_read_promotion)

def add_permissions_to_group_coordinator(grp_coordinator):
    permission_can_read_course = Permission.objects.get(name="Can view course")
    permission_can_add_course = Permission.objects.get(name="Can add course")
    permission_can_change_course = Permission.objects.get(name="Can change course")
    permission_can_delete_course = Permission.objects.get(name="Can delete course")

    permission_can_read_promotion = Permission.objects.get(name="Can view promotion")
    permission_can_add_promotion = Permission.objects.get(name="Can add promotion")
    permission_can_change_promotion = Permission.objects.get(name="Can change promotion")
    permission_can_delete_promotion = Permission.objects.get(name="Can delete promotion")

    permission_can_read_user = Permission.objects.get(name="Can view user")
    permission_can_add_user = Permission.objects.get(name="Can add user")
    permission_can_change_user = Permission.objects.get(name="Can change user")
    permission_can_delete_user = Permission.objects.get(name="Can delete user")
    
    grp_coordinator.permissions.add(permission_can_read_course)
    grp_coordinator.permissions.add(permission_can_add_course)
    grp_coordinator.permissions.add(permission_can_change_course)
    grp_coordinator.permissions.add(permission_can_delete_course)
    grp_coordinator.permissions.add(permission_can_read_promotion)
    grp_coordinator.permissions.add(permission_can_add_promotion)
    grp_coordinator.permissions.add(permission_can_change_promotion)
    grp_coordinator.permissions.add(permission_can_delete_promotion)
    grp_coordinator.permissions.add(permission_can_read_user)
    grp_coordinator.permissions.add(permission_can_add_user)
    grp_coordinator.permissions.add(permission_can_change_user)
    grp_coordinator.permissions.add(permission_can_delete_user)

app/templates/app/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    {% if title %}
        <title>GES - {{ title }}</title>
    {% else %}
        <title>GES</title>
    {% endif %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">GES</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Accueil</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Courses</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">My Profile</a>
                </li>
              {% endif %}
            </ul>


            <div class="nav-item">
              {% if request.user.is_authenticated %}
                <a class="nav-link text-dark" style="text-decoration: none;" href="/logout">Logout</a>
              {% else %}
                <a class="nav-link text-dark" style="text-decoration: none;" href="/login">Login</a>
              {% endif %}
            </div>
          </div>
        </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{  message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="container" style="height: calc(100vh - 56px);">
        {% block content %}{% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

app/templates/app/course/course.html
{% extends "app/base.html" %}
{% block content %}
<div class="container" style="height: calc(100vh - 56px);">
    <div class="d-flex justify-content-center align-items-center" style="height: 100%;">
      {% if perms.app.view_course %}
            {% for course in courses %}
                <p>{{ course.name }}</p>
            {% endfor %}
            {% else %}
                <h1>Vous n'avez pas la permission de voir les cours</h1>
            {% endif %}
        </div>
    </div>
{% endblock content %}

app/templates/app/create-user.html
{% extends "app/base.html" %}
{% block content %}
    <div class="d-flex justify-content-center align-items-center" style="height: 100%;">
        <div class="card" style="width: 32rem;">
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Create User</legend>
                            {{ form.as_p }}
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-outline-info" type="submit">Create</button>
                        </div>
                    </form>
                </div>
          </div>
    </div>
{% endblock content %}

app/templates/app/home.html
{% extends "app/base.html" %}
{% block content %}
    <div class="d-flex justify-content-center align-items-center" style="height: 100%;">
        COUCOU LE MONDE
        {{ request.user }}
    </div>
{% endblock content %}

app/templates/app/login.html
{% extends "app/base.html" %}
{% block content %}
    <div class="d-flex justify-content-center align-items-center" style="height: 100%;">
        <div class="card" style="width: 32rem;">
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Connexion</legend>
                            {{ form.as_p }}
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-outline-info" type="submit">Connexion</button>
                        </div>
                    </form>
                </div>
          </div>
    </div>
{% endblock content %}

app/templates/base.html
welcome to myges ! 

app/templates/coordinator/coordinator.html
Créer un student

app/templates/student/student.html
<h1>Mes promotions</h1>






<h1>Les matières de chaque promos</h1>

app/templates/teacher/teacher.html
<h1>liste de matières</h1>



<h1>liste des eleves de la matière</h1>